name: tests

on:
  push:
  pull_request:

jobs:
  run_tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # TODO : enable windows-latest
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Running Tests (windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        python test.py
    - name: Running Tests
      if: false == startsWith(matrix.os, 'windows')
      run: |
        python3 test.py

    name: ${{ matrix.os }} Python ${{ matrix.python }}
